{{- if .Values.rbac.create -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "downscaler.fullname" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ template "downscaler.fullname" . }}"
subjects:
- kind: ServiceAccount
  name: "{{ template "downscaler.fullname" . }}"
  namespace:  {{ .Values.namespace }}
{{- end -}}
