apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    application: {{.Values.application}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      application: {{.Values.application}}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        application: {{.Values.application}}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{.Values.serviceAccountName}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
          - --interval={{ .Values.interval }}
          - --namespace={{.Values.namespace }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 5m
              memory: 50Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
