apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "downscaler.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    type: deployment
    app: {{ template "downscaler.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "downscaler.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "downscaler.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "downscaler.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      containers:
        - name: {{ template "downscaler.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
          - --interval={{ .Values.interval }}
          - --namespace={{ .Values.namespace }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
