# Default values for downscaler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
name: kube-downscaler
namespace: opendata
interval: 5
rbac:
  ## If true, create & use RBAC resources
  create: true
  ## Ignored if rbac.create is true
  serviceAccountName: default
image:
  repository: hjacobs/kube-downscaler
  tag: 0.5
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 5m
    memory: 50Mi
securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
nodeSelector: {}
tolerations: []
affinity: {}
