replicaCount: 1

image:
  tag: development

  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 50Mi
securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
